In [1]:
import pandas as pd

Load the patient dataset and show summary with info().

In [2]:
Patient_data = pd.read_csv('/content/Patient_Data.csv')
Billing_data = pd.read_csv('/content/Billing_Data.csv')

In [3]:
Patient_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

In [5]:
Billing_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   PatientID         5 non-null      int64
 1   InsuranceCovered  5 non-null      int64
 2   FinalAmount       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [6]:
Patient_data.columns

Index(['PatientID', 'Name', 'Department', 'Doctor', 'BillAmount',
       'ReceptionistID', 'CheckInTime'],
      dtype='object')

In [7]:
Billing_data.columns

Index(['PatientID', 'InsuranceCovered', 'FinalAmount'], dtype='object')

2.	Select only the columns relevant for billing: ['PatientID', 'Department', 'Doctor', 'BillAmount'].

In [9]:
Patients_billing = Patient_data[['PatientID', 'Department', 'Doctor', 'BillAmount']]

3.	Drop administrative columns like ['ReceptionistID', 'CheckInTime'].

In [15]:
Patient_data.drop(columns=['ReceptionistID','CheckInTime'],inplace=True ,errors='ignore')

In [16]:
Patient_data

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN
5        101    Alice   Cardiology  Dr. Smith      5000.0

4.	Use groupby to find total bill amount per department.

In [17]:
department_total_bill = patients_billing.groupby('Department')['BillAmount'].sum()
print(department_total_bill)

Department
Cardiology     16200.0
Dermatology        0.0
Neurology          0.0
Orthopedics     7500.0
Name: BillAmount, dtype: float64

5.	Remove duplicate patient records based on PatientID.

In [19]:
Patient_data.drop_duplicates(subset=['PatientID'], inplace=True)
print("Duplicate patient records removed based on PatientID.")
print(Patient_data)

Duplicate patient records removed based on PatientID.
   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN

6.	Fill missing BillAmount values with the mean bill amount.

In [24]:
mean_bill = patients_billing['BillAmount'].mean()
patients_billing['BillAmount'].fillna(mean_bill)

0    5000.0
1    5925.0
2    7500.0
3    6200.0
4    5925.0
5    5000.0
Name: BillAmount, dtype: float64

7.	Merge the billing dataset with patient dataset on PatientID.

In [25]:
merged_data = pd.merge(Patient_data, Billing_data, on='PatientID')
print("Merged DataFrames:")
print(merged_data.head())

Merged DataFrames:
   PatientID     Name   Department     Doctor  BillAmount  InsuranceCovered  \
0        101    Alice   Cardiology  Dr. Smith      5000.0              2000
1        102      Bob    Neurology   Dr. John         NaN              1500
2        103  Charlie  Orthopedics    Dr. Lee      7500.0              2500
3        104    David   Cardiology  Dr. Smith      6200.0              3000
4        105      Eva  Dermatology   Dr. Rose         NaN              1000

   FinalAmount
0         3000
1         3500
2         5000
3         3200
4         4000

8.	Concatenate an additional DataFrame that contains new patients for the current week (row-wise).

In [27]:
new_patients_data = pd.DataFrame({
    'PatientID': [106, 107],
    'Name': ['Frank', 'Grace'],
    'Department': ['Orthopedics', 'Cardiology'],
    'Doctor': ['Dr. Lee', 'Dr. Smith'],
    'BillAmount': [8000.0, 5500.0]
})

Patient_data = pd.concat([Patient_data, new_patients_data], ignore_index=True)
print(Patient_data)

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN
5        106    Frank  Orthopedics    Dr. Lee      8000.0
6        107    Grace   Cardiology  Dr. Smith      5500.0
7        106    Frank  Orthopedics    Dr. Lee      8000.0
8        107    Grace   Cardiology  Dr. Smith      5500.0

9.	Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise).

In [31]:
patient_data_with_billing = pd.merge(
    Patient_data,
    Billing_data[['PatientID', 'InsuranceCovered', 'FinalAmount']],on='PatientID'
)

print(patient_data_with_billing.head(10))

   PatientID     Name   Department     Doctor  BillAmount  InsuranceCovered  \
0        101    Alice   Cardiology  Dr. Smith      5000.0              2000
1        102      Bob    Neurology   Dr. John         NaN              1500
2        103  Charlie  Orthopedics    Dr. Lee      7500.0              2500
3        104    David   Cardiology  Dr. Smith      6200.0              3000
4        105      Eva  Dermatology   Dr. Rose         NaN              1000

   FinalAmount
0         3000
1         3500
2         5000
3         3200
4         4000